### ISSUE TITLE
[Feat] 랜딩페이지 / 대시보드 화면 레이아웃 구성 (스타일 적용 전)

### ISSUE THREAD

**Issue by summerhater** [rkwhrcjsaud/ft_transcendence#38]
## ✏️ Description
대시보드와 랜딩페이지의 대락적 레이아웃 구성 적용

대시보드 - 그리팅 멘트, 전적, 프로필, 친구목록을 한번에 보여주는 페이지
랜딩페이지 - 사이트 처음 들어갔을때  & 네비게이션 바 왼쪽 상단 ft_transcendence 클릭했을 시 보여지는 화면

## ✅ Todo
- [x] 대시보드 화면에서 전적 보여주는 박스와 프로필 박스 나란히 배치하기
- [x] 전적 보여주는 박스 안에 greeting 멘트(시간대별로 멘트 변경)와 게임 전적 기록 넣기
- [x] 랜딩페이지에서 상단 네비게이션 안 보이게 처리 (공 사진 안에 버튼 배치로 대체)
