### ISSUE TITLE
[Feat]Dashboard 전반적인 레이아웃 구성 & 목데이터 생성 및 호출

### ISSUE THREAD

**Issue by summerhater** [rkwhrcjsaud/ft_transcendence#40]
## ✏️ Description

대시보드 페이지의 레이아웃 구성 만들기
 - greeting box
 - 프로필
 - 매치 히스토리
 - 친구목록 & 친구검색

## ✅ Todo
- [x] 위의 4요소 아코디언 형식으로 만들기
- [x] 각 요소마다 들어가야 하는 UI 적용
- [x] UI에 디자인 시안대로 스타일 적용
