### ISSUE TITLE
[Feat] 이메일 인증 기능 추가

### ISSUE THREAD

**Issue by rkwhrcjsaud** [rkwhrcjsaud/ft_transcendence#46]
## ✏️ Description

이메일을 통한 회원가입시 이메일 인증 창으로 이동하여 인증코드를 확인하고 user.is_verified를 True로 변경

## ✅ Todo
- [x] user.is_verified의 기본값을 false로 변경
- [x] 사용자의 이메일로 otp코드를 송신
- [x] 이메일 인증이 성공적으로 완료되면 user.is_verified를 true로 변경
