### ISSUE TITLE
[Feat] 친구 목록 관련 backend 구현

### ISSUE THREAD

**Issue by rkwhrcjsaud** [rkwhrcjsaud/ft_transcendence#62]
## ✏️ Description

친구를 일방적으로 추가하거나 제거하는 기능 추가

## ✅ Todo
- [ ] 어떤 사용자가 친구목록에 있는 지 저장하는 모델 추가
- [ ] 사용자를 친구로 추가하거나 제거하는 뷰 추가
- [ ] 친구의 목록을 가져오는 뷰 추가
