### ISSUE TITLE
[Fix] 프론트의 vanila JS & bootstrap을 사용한 리팩토링 진행(2.1) - 대시보드 Greeting Box, Profile

### ISSUE THREAD

**Issue by summerhater** [rkwhrcjsaud/ft_transcendence#69]
## ✏️ Description

대시보드의 greeting box, Profile을 바닐라 js와 bootstrap을 사용해 리팩토링

## ✅ Todo
- [ ] greeting box 리팩토링
- [ ] Profile 리팩토링
- [ ] 모든 영문자 폰트 'Roboto Mono' 설정
- [ ] loadCSS.js 작성해서 .js에 동적으로 css 스타일 멕이기
