### ISSUE TITLE
[Fix] 프론트의 vanila JS & bootstrap을 사용한 리팩토링 진행(2.3) - 대시보드 Friend List

### ISSUE THREAD

**Issue by summerhater** [rkwhrcjsaud/ft_transcendence#73]
## ✏️ Description

vanila JS & bootstrap을 사용해 기존의 대시보드 friend list 아코디언 리팩토링
(.tsx -> .js / scss -> css로 문법에 맞게 파일 수정)

## ✅ Todo
- [ ] 친구목록 (친구삭제 버튼, 온/오프라인 여부)
- [ ] 친구 검색창, 검색 결과 (친구추가/삭제 버튼)
- [ ] 친구 삭제 버튼 클릭 시 모달 윈도우
