### ISSUE TITLE
[Feat] verify 페이지 스타일 적용 및 마이너한 스타일 수정, 소셜 로그인 버튼 링크 연결

### ISSUE THREAD

**Issue by summerhater** [rkwhrcjsaud/ft_transcendence#98]
## ✏️ Description

verify 페이지 스타일 적용
마이너한 디자인 수정

## ✅ Todo
- [ ] verify 페이지 구조 그대로 유지하면서 css 적용하기
- [ ] 로그인 페이지 소셜 로그인 버튼 디자인 수정 및 "/42"로 링크 연결
- [ ] 가입 페이지 마이너한 스타일 조정
